# Generated by Django 4.2.1 on 2023-05-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_mesa',
            new_name='AddMesa',
        ),
    ]
