# Generated by Django 4.2.1 on 2023-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_produto_categoria_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='pedidos.produto'),
        ),
    ]
