# Generated by Django 4.2.1 on 2023-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_ativo_alter_produto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
